version: "3"
services:
  u18:
    # image: msojocs/ubuntu18-dtk-env:latest
    build:
      context: ./docker
      dockerfile: Dockerfile16
    volumes:
      - .:/workspace
      # - ./cache/.npm:/root/.npm
    environment:
      - ACTION_MODE=${ACTION_MODE:-false}
      # - https_proxy=${https_proxy:-}
      - LOCAL_USER_ID=${DOCKER_UID:-1000}
      - LOCAL_GROUP_ID=${DOCKER_GID:-1000}
    entrypoint: /workspace/docker/docker-entrypoint
    userns_mode: "host"
  u16:
    # image: ubuntu:16.04
    build:
      context: ./docker
      dockerfile: Dockerfile16
    volumes:
      - .:/workspace
      - /mnt/disk2/qt-test/qt-everywhere-opensource-src-5.15.3/qt-everywhere-src-5.15.3:/workplace/qt-src
      - /mnt/disk2/qt:/opt/Qt
    environment:
      - ACTION_MODE=${ACTION_MODE:-false}
      - LOCAL_USER_ID=${DOCKER_UID:-1000}
      - LOCAL_GROUP_ID=${DOCKER_GID:-1000}
    entrypoint: /workspace/docker/docker-entrypoint
    userns_mode: "host"