version: "3"
services:
  wechat_devtools:
    image: msojocs/ubuntu18-dtk-env:v1.0
    # build:
    #   context: ./docker
    #   dockerfile: Dockerfile
    volumes:
      - .:/workspace
      # - ./cache/.npm:/root/.npm
    environment:
      - ACTION_MODE=${ACTION_MODE:-false}
      # - https_proxy=${https_proxy:-}
      - LOCAL_USER_ID=${DOCKER_UID:-1000}
      - LOCAL_GROUP_ID=${DOCKER_GID:-1000}
    entrypoint: /workspace/docker/docker-entrypoint
    userns_mode: "host"